@api = https://localhost:5001/api

### Create account
POST {{api}}/users
Content-Type: application/json

{
    "username": "test123",
    "email": "test@test.com",
    "password": "test123"
}

### Sign-in
# @name sign_in
POST {{api}}/users/auth
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test123"
}

###
@accessToken = {{sign_in.response.body.$.token}}

### Get todos
GET {{api}}/todo
Authorization: Bearer {{accessToken}}

### Add todo
POST {{api}}/todo
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "test123",
    "project": "totallynewproject",
    "finishDate": "2021-04-11"
}

###
@todoId = 

### Delete todo
DELETE {{api}}/todo/{{todoId}}
Authorization:  Bearer {{accessToken}}
